version: '3.7'
services:
    postgres:
        container_name: chlovet-postgres
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        env_file: [.env, docker.env]
        networks: [postgres]
        image: postgres:12
        restart: always
        volumes:
            - "${APP_DIR}/data/pgsql_data:/data"
            - "${APP_DIR}/data/pgsql_backup:/backup"
        environment:
            PGDATA: "/data"
    phpfpm:
        container_name: chlovet-php-fpm
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        depends_on: [postgres]
        env_file: [.env, docker.env]
        networks: [postgres, php]
        working_dir: /var/www/html
        volumes:
            - "${APP_DIR}/app:/var/www/html"
    nginx:
        container_name: chlovet-nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        depends_on: [phpfpm]
        env_file: [.env, docker.env]
        image: nginx:1.17
        networks: [php, web]
        # On production, bind ports is your responsability.
        # ports: ["8180:80"]
        volumes:
            - "${APP_DIR}/app/public:/usr/share/nginx/html"
            - "${APP_DIR}/data/logs/nginx:/var/log/nginx"
networks:
    postgres:
    php:
