page_admin_list:
    path: /admin/page
    controller: App\Controller\PageAdminController::list
    methods: [GET, HEAD]

page_admin_revisions:
    path: /admin/page/{id}/revisions
    controller: App\Controller\PageAdminController::revisions
    methods: [GET, HEAD]

page_admin_append:
    path: /admin/page/{id}/edit
    controller: App\Controller\PageAdminController::append
    methods: [GET, HEAD, POST]

page_admin_delete:
    path: /admin/page/{id}/delete
    controller: App\Controller\PageAdminController::delete
    methods: [GET, HEAD, POST, DELETE]
