security_login:
    path: /security/signin
    controller: App\Controller\Admin\SecurityController::login

security_logout:
    path: /security/disconnect
    controller: App\Controller\Admin\SecurityController::logout
