parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $debug: "%kernel.debug%"

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Twig\:
        resource: '../src/Twig'
        tags: ['twig.extension', 'container.hot_path']

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
