parameters:
    app_file_directory: "%kernel.project_dir%/public/data"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $debug: "%kernel.debug%"
            $storageDirectory: "%app_file_directory%"

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Event\:
        resource: '../src/Event'
        tags: ['event.subscriber', 'container.hot_path']

    App\Twig\:
        resource: '../src/Twig'
        tags: ['twig.extension', 'container.hot_path']

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
