security_login:
    path: /security/signin
    controller: App\Controller\Admin\SecurityController::login

security_logout:
    path: /security/disconnect
    controller: App\Controller\Admin\SecurityController::logout

admin_debug_phpinfo:
    path: /admin/debug/phpinfo
    controller: App\Controller\Admin\SecurityController::phpinfo
