goat:
    runner:
        default:
              driver: ext-pgsql
              metadata_cache: apcu
              url: '%env(resolve:DATABASE_URL)%'
        logging:
              driver: ext-pgsql
              metadata_cache: apcu
              url: '%env(resolve:DATABASE_URL)%'
    query:
        enabled: true
    domain:
        enabled: false
        event_store: true
        lock_service: true
    preferences:
        enabled: true
        # schema:
        #     app.domain.some_variable:
        #         label: Some variable
        #         description: Uncheck this value to deactive this feature
        #         type: bool
        #         collection: false
        #         default: true
