security:
    providers:
        caporal_chef:
            id: App\Security\ChefUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: caporal_chef
            guard:
                entry_point: App\Security\ChefAuthenticator
                authenticators:
                    - App\Security\ChefAuthenticator
            logout:
                path: security_logout

    access_control:
        - { path: ^/admin, roles: ROLE_CHEF }
